#!/bin/bash

IMAGE_NAME="postgres"
PG_VERSION="9.3"

# Pull docker image
docker pull #IMAGE_NAME:$PG_VERSION

# Build docker image
#IMAGE_PATH="github.com/mobula/docker-postgresql-postgis"
#docker build -q=true -t $IMAGE_NAME $IMAGE_PATH
